//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APSWDatabaseEntities : DbContext
    {
        public APSWDatabaseEntities()
            : base("name=APSWDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarms> Alarms { get; set; }
        public virtual DbSet<AnalogChannelsScaling> AnalogChannelsScaling { get; set; }
        public virtual DbSet<AuxiliaryResults> AuxiliaryResults { get; set; }
        public virtual DbSet<CustomTest> CustomTest { get; set; }
        public virtual DbSet<ExecutionAuxiliaryResults> ExecutionAuxiliaryResults { get; set; }
        public virtual DbSet<ExecutionParameters> ExecutionParameters { get; set; }
        public virtual DbSet<ExecutionResults> ExecutionResults { get; set; }
        public virtual DbSet<Executions> Executions { get; set; }
        public virtual DbSet<GlobalParameters> GlobalParameters { get; set; }
        public virtual DbSet<MainConfigurations> MainConfigurations { get; set; }
        public virtual DbSet<MiscDataLocal> MiscDataLocal { get; set; }
        public virtual DbSet<MiscDataTest> MiscDataTest { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<ParametersValues> ParametersValues { get; set; }
        public virtual DbSet<PartNumbers> PartNumbers { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Phases> Phases { get; set; }
        public virtual DbSet<PNProperties> PNProperties { get; set; }
        public virtual DbSet<PNSNProperties> PNSNProperties { get; set; }
        public virtual DbSet<PNTests> PNTests { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<ResultsConstraints> ResultsConstraints { get; set; }
        public virtual DbSet<ResultStatuses> ResultStatuses { get; set; }
        public virtual DbSet<RolePermissions> RolePermissions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SerialNumbers> SerialNumbers { get; set; }
        public virtual DbSet<ShowedAuxiliaryResults> ShowedAuxiliaryResults { get; set; }
        public virtual DbSet<SNGenerator> SNGenerator { get; set; }
        public virtual DbSet<SNInformations> SNInformations { get; set; }
        public virtual DbSet<SNProperties> SNProperties { get; set; }
        public virtual DbSet<SNTestPhases> SNTestPhases { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestCompositionProperties> TestCompositionProperties { get; set; }
        public virtual DbSet<TestCompositionPropertiesValues> TestCompositionPropertiesValues { get; set; }
        public virtual DbSet<TestCompositions> TestCompositions { get; set; }
        public virtual DbSet<TestPhases> TestPhases { get; set; }
        public virtual DbSet<TestProperties> TestProperties { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
