//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxiliaryResults
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuxiliaryResults()
        {
            this.ShowedAuxiliaryResults = new HashSet<ShowedAuxiliaryResults>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Index { get; set; }
        public int Decimals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowedAuxiliaryResults> ShowedAuxiliaryResults { get; set; }
    }
}
