//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionAuxiliaryResults
    {
        public int ID { get; set; }
        public int ExecutionResult { get; set; }
        public string Name { get; set; }
        public int Index { get; set; }
        public bool Show { get; set; }
        public double DoubleValue { get; set; }
        public int Decimals { get; set; }
    
        public virtual ExecutionResults ExecutionResults { get; set; }
    }
}
