//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Executions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Executions()
        {
            this.ExecutionParameters = new HashSet<ExecutionParameters>();
            this.ExecutionResults = new HashSet<ExecutionResults>();
        }
    
        public int ID { get; set; }
        public int SerialNumber { get; set; }
        public int SNTestPhase { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int ResultStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionParameters> ExecutionParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionResults> ExecutionResults { get; set; }
        public virtual ResultStatuses ResultStatuses { get; set; }
        public virtual SerialNumbers SerialNumbers { get; set; }
        public virtual SNTestPhases SNTestPhases { get; set; }
    }
}
