//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionResults
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExecutionResults()
        {
            this.ExecutionAuxiliaryResults = new HashSet<ExecutionAuxiliaryResults>();
        }
    
        public int ID { get; set; }
        public int Execution { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Index { get; set; }
        public int ReportIndex { get; set; }
        public int Decimals { get; set; }
        public bool BoolExpected { get; set; }
        public double Min { get; set; }
        public double Max { get; set; }
        public string StringsExpected { get; set; }
        public byte[] GraphBands { get; set; }
        public bool BoolValue { get; set; }
        public int IntValue { get; set; }
        public double DoubleValue { get; set; }
        public string StringValue { get; set; }
        public byte[] GraphValue { get; set; }
        public int ResultStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionAuxiliaryResults> ExecutionAuxiliaryResults { get; set; }
        public virtual ResultStatuses ResultStatuses { get; set; }
        public virtual Types Types { get; set; }
        public virtual Executions Executions { get; set; }
    }
}
