//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNTests
    {
        public int ID { get; set; }
        public int PartNumber { get; set; }
        public int Test { get; set; }
        public bool Default { get; set; }
    
        public virtual PartNumbers PartNumbers { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
