//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsConstraints
    {
        public int ID { get; set; }
        public int TestPhase { get; set; }
        public int Result { get; set; }
        public bool BoolExpected { get; set; }
        public double Min { get; set; }
        public double Max { get; set; }
        public string StringsExpected { get; set; }
        public byte[] GraphBands { get; set; }
        public bool Enable { get; set; }
    
        public virtual Results Results { get; set; }
        public virtual TestPhases TestPhases { get; set; }
    }
}
