//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermissions
    {
        public int ID { get; set; }
        public int Role { get; set; }
        public int Permission { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
