//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowedAuxiliaryResults
    {
        public int Result { get; set; }
        public int AuxiliaryResult { get; set; }
        public bool Show { get; set; }
    
        public virtual AuxiliaryResults AuxiliaryResults { get; set; }
        public virtual Results Results { get; set; }
    }
}
