//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNTestPhases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SNTestPhases()
        {
            this.Executions = new HashSet<Executions>();
        }
    
        public int ID { get; set; }
        public int SNInformation { get; set; }
        public int Index { get; set; }
        public string TestPhaseName { get; set; }
        public string TestPhaseDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Executions> Executions { get; set; }
        public virtual SNInformations SNInformations { get; set; }
    }
}
