//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCompositionProperties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCompositionProperties()
        {
            this.TestCompositionPropertiesValues = new HashSet<TestCompositionPropertiesValues>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Index { get; set; }
    
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCompositionPropertiesValues> TestCompositionPropertiesValues { get; set; }
    }
}
